src/main/java/com/alkemy/ong/entity/TestimonialEntity.java
src/main/java/com/alkemy/ong/entity/TestimonyEntity.java
src/main/java/com/alkemy/ong/repository/TestimonyRepository.java

Estructura de datos : creacion de la entidad Testimonials

Creation Testimonials Entity

---

src/main/java/com/alkemy/ong/entity/NewsEntity.java
src/main/java/com/alkemy/ong/repository/NewsRepository.java
src/main/resources/application.properties

**Sumary**
- Created entity News
- Created repository NewsRepository
- Adding applications.properties

Created entity News and repository NewsRepository

---

pom.xml
src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/auth/controller/UserAuthController.java
src/main/java/com/alkemy/ong/auth/service/UserDetailsCustomService.java
src/main/java/com/alkemy/ong/entity/UserEntity.java
src/main/java/com/alkemy/ong/repository/UserRepository.java

**SUMARY**
- Registration  POST /auth/register, return user
- Validations (Adding dependency validation) in model UserEntity
- Password encryption.
- Storage in the database.

Registration, validations, validation dependency inclusion in pom, password encryption, storage in the database.

---

src/main/java/com/alkemy/ong/entity/RoleEntity.java
src/main/java/com/alkemy/ong/repository/RoleRepo.java
src/main/java/com/alkemy/ong/repository/RoleRepository.java

I added RoleEntity with its attributes and relations

Added Role entity

---

src/main/java/com/alkemy/ong/entity/SlideEntity.java
src/main/java/com/alkemy/ong/repository/SlideRepo.java

I added the Slide Entity with relations and the repository

Added Slide Entity and Slide Repository

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/auth/service/UserDetailsCustomService.java
src/main/java/com/alkemy/ong/repository/UserRepository.java

**Summary**
- Added security configuration to route access by assigned roles.
(Roles: ADMIN,USER).
- Complete the SecurityConfiguration file so that 403 error is returned in case of being in an unauthorized path.
- Add repository email search.

Security Configuration Update

---

pom.xml
src/main/java/com/alkemy/ong/controller/OrganizationController.java
src/main/java/com/alkemy/ong/dto/OrganizationDto.java
src/main/java/com/alkemy/ong/entity/OrganizationEntity.java
src/main/java/com/alkemy/ong/entity/RoleEntity.java
src/main/java/com/alkemy/ong/mapper/OrganizationMapper.java
src/main/java/com/alkemy/ong/service/OrganizationService.java

- Added MapStruck Dependencies to Pom. 
- Added OrganizationDto class.
- Added OrganizationMapper interface.
- Added OrganizationController with endpoint that retrieve the public information about an Organization.
- Added OrganizationService.
- Fix "where" clause on OrganizationEntity.

EndPoint Organization

---

src/main/java/com/alkemy/ong/auth/service/UserDetailsCustomService.java

Adding roleId in register

---

src/main/java/com/alkemy/ong/entity/RoleEntity.java

Deleted the list of UserEntities from RoleEntity

Deleted bidirectional relationship between UserEntity and RoleEntity

---

src/main/java/com/alkemy/ong/auth/controller/UserAuthController.java
src/main/java/com/alkemy/ong/auth/domain/RoleDomain.java
src/main/java/com/alkemy/ong/auth/domain/UserDomain.java
src/main/java/com/alkemy/ong/auth/dto/UserDTO.java
src/main/java/com/alkemy/ong/auth/mapper/RoleMapper.java
src/main/java/com/alkemy/ong/auth/mapper/UserMapper.java
src/main/java/com/alkemy/ong/auth/service/UserDetailsCustomService.java
src/main/java/com/alkemy/ong/entity/RoleEntity.java
src/main/java/com/alkemy/ong/entity/UserEntity.java
src/main/java/com/alkemy/ong/repository/UserRepository.java

Dentro del Packeage auth que contiene todos los metodos para registrar un usuario y loguearse, se agrego:
• Package mapper y clase UserMapper y RoleMapper para gestionar los DTOs de entrada y salida. 
•Package Domain y clase UserDomain y RoleDomain para recibir y gestionar los datos recibidos en la peticion y compararlos con los datos persistidos en la BD para realizar las respectivas validaciones. 
metodo Login Funcionando Correctamente.

Arreglos en el ENDPOINT login User 

---

src/main/java/com/alkemy/ong/controller/UserController.java
src/main/java/com/alkemy/ong/service/UserService.java
src/main/java/com/alkemy/ong/service/impl/IUserService.java

Added method delete for User, added a UserController, UserService and implementation

Added Endpoint to delete User with its id

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/controller/OrganizationController.java
src/main/java/com/alkemy/ong/dto/OrganizationDto.java
src/main/java/com/alkemy/ong/mapper/ActivityMapper.java
src/main/java/com/alkemy/ong/mapper/OrganizationMapper.java
src/main/java/com/alkemy/ong/service/OrganizationService.java
src/main/java/com/alkemy/ong/service/impl/ActivityServiceImpl.java

**Summary**
- Creation of interface Entity to dto.
- Creation of service for update entity Organization.
- Creation of the route to update the data of the Organization.
- Modification of the security so that the data update of the Organization entity is accessible only by the ADMIN role.

EndPoint for updating public data of Organization

---

src/main/java/com/alkemy/ong/auth/mapper/UserMapper.java
src/main/java/com/alkemy/ong/controller/UserController.java
src/main/java/com/alkemy/ong/service/UserService.java
src/main/java/com/alkemy/ong/service/impl/IUserService.java

Add method for the udate user for id and annotation Path 
response with error 404

add method update for id in the file UserController.java

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/controller/CategoryController.java
src/main/java/com/alkemy/ong/dto/CategoryDto.java
src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
src/main/java/com/alkemy/ong/service/CategoryService.java

**Summary**
- Creation of interface Entity to dto for Category.
- Creation of service for get all entity Category.
- Creation of the route to getall the data Categories.
- Modification of the security so that the getAll of the Categories entity is accessible only by the ADMIN role.

Endopoint List of Categories

---

src/main/java/com/alkemy/ong/entity/MemberEntity.java

Small update for the MemberEntity with softDelete query

Updated MemberEntity with SQL solfDelete and where clause

---

src/main/java/com/alkemy/ong/controller/NewsController.java
src/main/java/com/alkemy/ong/dto/NewsDTO.java
src/main/java/com/alkemy/ong/mapper/NewsMapper.java
src/main/java/com/alkemy/ong/service/NewsService.java
src/main/java/com/alkemy/ong/service/impl/INewsService.java

Added NewsController, NewsDTO, NewsService and implementation, NewsMapper using mapstruct dependency for the endpoing Get to see news by id for an Admin

Added get endpoint for admin to see news by id

---

src/main/java/com/alkemy/ong/mapper/UserMapper.java

Arreglo de mapper para arreglar conflicto con método de UserController update.

update mapper source package

---

src/main/java/com/alkemy/ong/controller/BucketController.java
src/main/resources/application.properties

**SUMMARY**
- Add BucketController
- Fixes in application.properties

I added integration of th AmazonClient service methods

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/controller/NewsController.java
src/main/java/com/alkemy/ong/controller/UserController.java
src/main/java/com/alkemy/ong/entity/NewsEntity.java
src/main/java/com/alkemy/ong/service/impl/NewsServiceImpl.java

Also deleted @PreAuthorize from UserController
All new Endpoints should be added in the corresponding list

Added Role Validation through HttpSecurity

---

src/main/java/com/alkemy/ong/controller/CategoryController.java
src/main/java/com/alkemy/ong/dto/CategoryDto.java
src/main/java/com/alkemy/ong/dto/CategoryDtoFull.java
src/main/java/com/alkemy/ong/entity/CategoryEntity.java
src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
src/main/java/com/alkemy/ong/service/CategoryService.java

**Summary**
- Creation CategoryEntityDtoFull.
- Modify CategoryMapper for CategoryEntityFullDto.
- Creation of method in CategoryService to update the Category entity.
- Creation of the route in Controller for updating the Category enitity.

Update Category For ID

---

src/main/java/com/alkemy/ong/controller/UserController.java
src/main/java/com/alkemy/ong/service/UserService.java
src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java

add endpoint in UserController
add inplement UserService 
add method in UserService Implement

add change for endpoint get auth/me

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/controller/CategoryController.java
src/main/java/com/alkemy/ong/service/CategoryService.java
src/main/resources/application.properties

-Added endpoint in controller to get category by ID.
-Added Service to check if category exist and retrieve it from DB.
-Added authority permision to access the endpoint just to ADMIN.

Add endpoint to get categories by id

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/controller/SlideController.java
src/main/java/com/alkemy/ong/dto/SlideBasicDto.java
src/main/java/com/alkemy/ong/entity/SlideEntity.java
src/main/java/com/alkemy/ong/mapper/SlideMapper.java
src/main/java/com/alkemy/ong/service/SlideService.java

Added Endpoint to retrieve Slides only image and order by an Admin

---

src/main/java/com/alkemy/ong/dto/ContactDto.java
src/main/java/com/alkemy/ong/entity/ContactEntity.java
src/main/java/com/alkemy/ong/mapper/ContactMapper.java
src/main/java/com/alkemy/ong/repository/ContactRepository.java
src/main/java/com/alkemy/ong/service/ContactService.java

I add necessary files to capture contact data and method to persist in database
Files Add: 
ContacEntity, Contact.dto, ContactMapper, ContactRepository, ContactService

I add files to persist contact data of the form

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/controller/UserController.java
src/main/java/com/alkemy/ong/service/UserService.java

modified methods and files SecurityConfiguration, UserController and UserService
evidence

Endpoint auth/me working

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/controller/SlideController.java
src/main/java/com/alkemy/ong/repository/SlideRepository.java
src/main/java/com/alkemy/ong/service/SlideService.java

Endpoint Delete Slides by Id for Admi
n

Added the deletion method by id for Admin only

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/controller/ActivityController.java
src/main/java/com/alkemy/ong/dto/ActivityDto.java
src/main/java/com/alkemy/ong/dto/ActivityDtoFull.java
src/main/java/com/alkemy/ong/mapper/ActivityMapper.java
src/main/java/com/alkemy/ong/service/ActivityService.java

Summary:
- method implementation in controller
- implementation of validation in the ActivityDto
- method implementation in ActivityDto
- implementation of mappings with mapstruct
- added path to securityConfig to allow access to admin role

[OT147-50] EndPoint:  Actitities creation

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/controller/NewsController.java
src/main/java/com/alkemy/ong/service/NewsService.java

**Summary**
- Creation of the Controller route to update News Entity.
- Creation of the method in the service to update a News entity.
- Add the route to the security so that update the entity is only for the Admin role.

Ot 147 47 Update News Entity

---

src/main/java/com/alkemy/ong/controller/SlideController.java
src/main/java/com/alkemy/ong/entity/ContactEntity.java
src/main/java/com/alkemy/ong/mapper/SlideMapper.java
src/main/java/com/alkemy/ong/service/SlideService.java
src/main/java/com/alkemy/ong/service/UserService.java

Updated import and fixe some compiling errors

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/controller/NewsController.java
src/main/java/com/alkemy/ong/service/NewsService.java

**Summary**
- Creation of the Controller route to delee News Entity.
- Creation of the method in the service to delete a News entity.
- Add the route to the security so that delete the entity is only for the Admin role.

Ot 147 48 Delete New entity

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/controller/SlideController.java
src/main/java/com/alkemy/ong/dto/SlideDtoFull.java
src/main/java/com/alkemy/ong/entity/SlideEntity.java
src/main/java/com/alkemy/ong/service/SlideService.java

Summary:
-Added service to retrieve  a Slide with a given id.
-Added endpoint which call the service.
-Modifided SlideEntity fecht property.
-Modifided SlideFullDto.
-Added route to permit access only to Admin user.
Below there is evidence of the endpoint working.

Addes service to retrieve Slide with a given id, and also controller

---

src/main/java/com/alkemy/ong/controller/OrganizationController.java
src/main/java/com/alkemy/ong/mapper/SlideMapper.java
src/main/java/com/alkemy/ong/repository/SlideRepository.java
src/main/java/com/alkemy/ong/service/SlideService.java

Add query custom in SlideRepository
add method in the SlideMapper
add method in the SlideService
Evidence for function
change in the organizationController endpoint("public/{id}")

OT147-60 Add Slide list in the endpoint Organization public

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/controller/ContactController.java
src/main/java/com/alkemy/ong/entity/ContactEntity.java
src/main/java/com/alkemy/ong/mapper/ContactMapper.java
src/main/java/com/alkemy/ong/service/ContactService.java

Add endpoints  list contacts in the ConstactControlller.
Add method to process contact list in ServiceContact file.
Change in ContactEntity the @Column annotation from unique to false.
add endpoint in the SecurityConfig for Admin.

OT147-61 | Add list contacts endpoint for Admin

---

src/main/java/com/alkemy/ong/entity/ActivityEntity.java
src/main/java/com/alkemy/ong/seeder/ActivitiesSeeder.java

**SUMARY**
- Created ActivitiesSeeder
- Constructor in ActivityEntity
- package seed

Created ActivitiesSeeder, constructor in ActivityEntity and package seed

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/controller/TestimonialController.java
src/main/java/com/alkemy/ong/dto/TestimonialDto.java
src/main/java/com/alkemy/ong/mapper/TestimonialMapper.java
src/main/java/com/alkemy/ong/service/TestimonialService.java

**SUMARY**
- Added TestimonialService
- Added TestimonialDto
- Added TestimonialMapper
- Added TestimonialController
- Added path in SecurityConfig

Adding Post/testimonials

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/controller/MemberController.java
src/main/java/com/alkemy/ong/entity/MemberEntity.java
src/main/java/com/alkemy/ong/mapper/MemberMapper.java
src/main/java/com/alkemy/ong/service/MemberService.java
src/main/java/com/alkemy/ong/service/NewsService.java
src/main/java/com/alkemy/ong/service/OrganizationService.java

Summary:
- method implementation in controller "getAllMembers"
- method implementation in memberService "getAllMembers" 
- Changed sql sentences and softDelete clause to soft_delete for proper database persistence.
**Evidence**

[OT147-68] methods to get a list of members

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/controller/TestimonialController.java
src/main/java/com/alkemy/ong/entity/TestimonialEntity.java
src/main/java/com/alkemy/ong/service/TestimonialService.java

**SUMARY**
- Added method to modify testimonial
- Added @Transactional annotation in save and update methods.
- Added path in SecurityConfig for user admin
- Modification of TestimonialEntity due to error with softDelete.

Ot147 66-> PUT/testimonials/:id 

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/controller/MemberController.java
src/main/java/com/alkemy/ong/service/MemberService.java

Summary:
- method implementation in controller "delete" @DeleteMapping("/{id}")
- add method in MemberService "deleteMemberById" 
**Evidence**

[OT147-70] added method for soft_delete member by id

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/controller/RestExceptionHandler.java
src/main/java/com/alkemy/ong/controller/TestimonialController.java
src/main/java/com/alkemy/ong/dto/APIErrorDto.java
src/main/java/com/alkemy/ong/exceptions/ParamNotFound.java
src/main/java/com/alkemy/ong/service/TestimonialService.java

**SUMARY**
- Added method to delete a testimonial
- Added exceptions package
- Added RestExceptionHandler class to unify exceptions.
- Added ParamNotFound class in exceptions package
- Modification of the validate method to use own exceptions.
- Added path in SecurityConfig for user admin

Adding DELETE/testimonials/:id

---

src/main/java/com/alkemy/ong/controller/OrganizationController.java
src/main/java/com/alkemy/ong/dto/OrganizationPublicDto.java
src/main/java/com/alkemy/ong/dto/OrganizationUpdateDto.java
src/main/java/com/alkemy/ong/dto/SlidePublicOrganizationDto.java
src/main/java/com/alkemy/ong/entity/OrganizationEntity.java
src/main/java/com/alkemy/ong/mapper/OrganizationMapper.java
src/main/java/com/alkemy/ong/mapper/SlideMapper.java
src/main/java/com/alkemy/ong/service/OrganizationService.java
src/main/java/com/alkemy/ong/service/SlideService.java

-Added member variables to OrganizationEntity:
> Facebook Url
> Instragram Url
> LinkedIn Url
**-** Added OrganizationPublicDto with public fields of Organization
**-** Added SlideOrganizationPublicDto. Slide with the public fields of Organization.
**-** Modified method to update an Organization because of the new parameters.
**-** Modified method to retrieve a slide with the  corresponding Organization, because of the new parameters.
**-** Modified OrganizationMapper, because of the new parameters.
**-** Modified SlideMapper, because of the new parameters.
**-** Modified OrganizationController to call the modified methods.

OT147-63 Added social network URL to Organization

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/controller/MemberController.java
src/main/java/com/alkemy/ong/entity/ActivityEntity.java
src/main/java/com/alkemy/ong/service/MemberService.java

Summary:
- method implementation in controller @PutMapping("/{id}")  "update"
- implementation of validation in the memberDto class
- implementation of validation in memberService by ID in method "update" .
- implementation of ParamNotFound and @Valid to send an error description to the user view
**Evidence**

[OT147-71] EndPoint member Update

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/controller/CommentController.java
src/main/java/com/alkemy/ong/dto/CommentDto.java
src/main/java/com/alkemy/ong/mapper/CommentMapper.java
src/main/java/com/alkemy/ong/service/CommentService.java

**Summary**
- Controller creation for Comment.
- Creation of the route to create Comment.
- Creation method service for creation of CommentEntity.
- Creation Dto fot CommentEntity.
- Creation Mapper for CommentEntity.
- Add path to security only accessible for User role.

Creation Comment entity complete ticket OT-147-76

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/controller/CommentController.java
src/main/java/com/alkemy/ong/dto/CommentBodyDto.java
src/main/java/com/alkemy/ong/dto/CommentDto.java
src/main/java/com/alkemy/ong/mapper/CommentMapper.java
src/main/java/com/alkemy/ong/repository/CommentRepository.java
src/main/java/com/alkemy/ong/service/CommentService.java

**Summary**
- Creation of the route to Get all  Comments.
- Creation method service for Get All of CommentEntity.
- Creation DtoBody fot CommentEntity.
- Creation Mapper DtoBody for CommentEntity.
- Add Query to order in the repository.
- Add path to security only accessible for User ADMIN.

Get all  Comment only for Admin Ticket 75)

---

src/main/java/com/alkemy/ong/controller/CategoryController.java
src/main/java/com/alkemy/ong/service/CategoryService.java

-Added Service for pagination of categories.
-Added Controller endpoint for pagination of categories.
**_Methods in action_**

OT-147-80: Pagination for Categories

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/controller/NewsController.java
src/main/java/com/alkemy/ong/mapper/NewsMapper.java
src/main/java/com/alkemy/ong/service/NewsService.java

adding methods and changes for news pagination
add a controller to show list of new items per page
also add method to list and show link next and previous page
add path to page security

add pagination news

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java

change the endpoints of Role Admin from post, put, delete protecting them with jwt.
User endpoint optimization

protected endpoint width jwt->OT147-73

---

pom.xml
src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/config/SwaggerConfig.java

**Summary**
- Append new dependencies to generate documentation with Swagger.
- Creation of the class for the configuration of Swagger.
- Modification of the paths for Swagger.

Configuration Swagger for documentation(Ticket complete OT-147-84)

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java

revert change in the endpoint

---

src/main/java/com/alkemy/ong/controller/NewsController.java
src/main/java/com/alkemy/ong/util/DocumentationMessages.java

Summary:
-Added final variables to the file DocumentationMessages.
-Added documentations tags to NewsController.

Added documentation tags to News Controller

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/controller/CategoryController.java
src/main/java/com/alkemy/ong/dto/CategoryDtoFull.java
src/main/java/com/alkemy/ong/service/CategoryService.java
src/main/java/com/alkemy/ong/util/DocumentationMessages.java

Also implemented ParamNotFound to get the errors and added verifications to CategoryFullDto field nam
e

Added Documentation tags to Category Controller

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/controller/CategoryController.java
src/main/java/com/alkemy/ong/dto/CategoryDtoFull.java
src/main/java/com/alkemy/ong/service/CategoryService.java
src/main/java/com/alkemy/ong/util/DocumentationMessages.java

Reverts alkemyTech/OT147-SERVER#104 problems with testing

Revert "Added Documentation tags to Category Controller"

---

src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
src/main/java/com/alkemy/ong/controller/UserController.java
src/main/java/com/alkemy/ong/service/UserService.java

I reviewed all endpoints and solved a UserController path controller issue
Evidence in zip:
[Endpoint  Check.postman_collection.zip](https://github.com/alkemyTech/OT147-SERVER/files/8294955/Endpoint.Check.postman_collection.zip)

Ot147 73->Resolving JWT endpoint protection, Pach User fix

---

src/main/java/com/alkemy/ong/controller/TestimonialController.java
src/main/java/com/alkemy/ong/dto/TestimonialDto.java
src/main/java/com/alkemy/ong/service/TestimonialService.java
src/main/java/com/alkemy/ong/util/DocumentationMessages.java

**SUMARY**
- Validations in TestimonialDto
- Fixes in DocumentsMessages, in Testimonial and comments in TestimonialController
- Removed validation in TestimonialService

BugO147-65 and OT147-66 resolved

---

pom.xml
src/main/java/com/alkemy/ong/util/DocumentationResponse.java
src/test/java/com/alkemy/ong/controller/TestimonialControllerTest.java
src/test/java/com/alkemy/ong/mapper/TestimonialMapperTest.java

**SUMARY**
- Added dependency in pom
- Added package test
- Added TestimonialMapperTest and TestimonialControllerTest, Coverage 100%
- Added constant USER and ADMIN in DocumentationResponse for test.

OT147-98 Test Testimonial

---

src/main/java/com/alkemy/ong/auth/controller/UserAuthController.java
src/main/java/com/alkemy/ong/controller/UserController.java
src/main/java/com/alkemy/ong/service/UserService.java
src/main/java/com/alkemy/ong/util/DocumentationMessages.java

Add Endpoint authentification documentation swagger

Add documentation to Authentication Ot147 89

---

src/test/java/com/alkemy/ong/auth/controller/UserAuthControllerTest.java

**SUMARY**
- AuthController test
- 100% coverage in register and login methods.
- Checked validations.

OT147-96 AuthControllerTest

---

src/main/java/com/alkemy/ong/controller/ContactController.java
src/test/java/com/alkemy/ong/controller/MemberControllerTest.java
src/test/java/com/alkemy/ong/util/TestEntitiesCreation.java

•I add @Valid annotation in ContactController class to perform the corresponding validations in the ContactDTO

[Ot147-100] bug OT147-54

---

src/main/java/com/alkemy/ong/controller/UserController.java
src/main/java/com/alkemy/ong/service/UserService.java

Change in the endpoint update UserDTO for UserDto a file UserController
Change in the methods updateUser UserDTO for UserDto a file UserService

change UserDTO for UserDto in UserController and UserService

---

src/main/java/com/alkemy/ong/controller/CategoryController.java
src/main/java/com/alkemy/ong/dto/CategoryDto.java
src/main/java/com/alkemy/ong/dto/CategoryDtoFull.java
src/main/java/com/alkemy/ong/service/CategoryService.java
src/main/java/com/alkemy/ong/util/DocumentationMessages.java

Change Category Service to reuse code and get messages from validation
s

Added documentation tags to Category Controller and validations to Dtos

---

src/test/java/com/alkemy/ong/controller/MemberControllerTest.java

**SUMMARY**
•The implementation of a test is missing in the exception to reach 100% coverage in the lines of code
•Evidence

[OT147-91] => Pr MemberControllerTest class

---

src/main/java/com/alkemy/ong/mapper/ActivityMapper.java
src/main/java/com/alkemy/ong/service/ActivityService.java

Refactor Mapper to be more efficient

Deleted duplicate method in Activity Mapper

---

src/main/java/com/alkemy/ong/dto/OrganizationPublicDto.java
src/main/java/com/alkemy/ong/entity/OrganizationEntity.java
src/test/java/com/alkemy/ong/controller/OrganizationControllerTest.java
src/test/java/com/alkemy/ong/mapper/OrganizationMapperTest.java
src/test/java/com/alkemy/ong/util/OrganizationMock.java

Added Organization Controller testing

---

src/main/java/com/alkemy/ong/mapper/ActivityMapper.java
src/main/java/com/alkemy/ong/service/ActivityService.java
src/test/java/com/alkemy/ong/controller/ActivityControllerTest.java
src/test/java/com/alkemy/ong/mapper/ActivityMapperTest.java
src/test/java/com/alkemy/ong/util/ActivityMock.java

Ot 147 94 Added Activity Mapper Test and Activity Controller Test 

---

src/test/java/com/alkemy/ong/controller/CategoryControllerTest.java
src/test/java/com/alkemy/ong/mapper/CategoryMapperTest.java

**Summary**
- Add Mapper test with 100% coverage.
- Add Controller test with 100% coverage.

Ticket Test mapper and controller complete

---

pom.xml
src/test/java/com/alkemy/ong/controller/CategoryControllerTest.java

Added Jacoco dependency to get coverage information

Ot 147 test exclusion

---

src/test/java/com/alkemy/ong/controller/SlideControllerTest.java
src/test/java/com/alkemy/ong/util/SlideMock.java

**- Summary**
- Add SlideMock.
- Add SlideController Test complete 100% coverage.

Test complete Slide Controller

---

src/test/java/com/alkemy/ong/controller/BucketControllerTest.java

Summary:
-Added bucketController test.

Added BucketControllerTest

---

src/test/java/com/alkemy/ong/controller/MemberControllerTest.java

 Updated Member Controller Test to 100% coverage
